- name: disbale anginx and enable particular version
  shell: dnf module disable nginx -y; dnf module enable nginx:1.24 -y

- name: install nginx
  dnf:
    name: nginx
    state: latest

- name: copy nginx file 
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: remove html folder of default content 
  file:
    path: /usr/share/nginx/html
    state: absent 

- name: creating directory html
  file:
    path: /usr/share/nginx/html
    state: directory

- name: download and extract file 
  unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: enable and start nginx module
  systemd_service:
    name: nginx
    state: started
    enabled: true
