- name: copy rabbitmq repo file
  copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbitmq server
  dnf:
    name: rabbitmq-server
    state: latest

- name: start rebbitmq server
  systemd_service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: add user to rabbitmqctl
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present