- name: install mysql server
  dnf:
    name: mysql-server
    state: latest

- name: mysql enable and start systemctl
  systemd_service:
    name: mysqld
    state: started
    enabled: true 

- name: set password for mysql 
  shell: mysql_secure_installation --set-root-pass RoboShop@1