
- name: include nodejs role from common 
  include_role:
    name: common
    tasks_from: nodejs.yml

- name: copy mongo db file
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: dnf install mongo db
  dnf:
    name: mongodb-mongosh
    state: latest

- name: load master data
  shell: mongosh --host mongodb-dev.harshaldevops.online </app/db/master-data.js

- name: perform systemd_setup
  include_role:
    name: common
    tasks_from: systemd_setup.yml
