- name: get docker repo file
  get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker
  dnf:
    name: docker-ce
    state: installed

- name: start docker
  systemd_service:
    name: docker
    state: started
    enabled: true