- name: install golang 
  dnf:
    name: golang
    state: latest

- name: invoke app_pre_setup task in common
  invoke_tasks:
    name: app_pre_setup.yml

- name: build the golang component 
  shell: go mod init {{ app_name }} ; go get ; go build