- name: install python 
  dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: latest

- name: invoke app_pre_setup task 
  include_tasks:
    file: app_pre_setup.yml

- name: install pip3 
  shell: pip3 install -r requirements.txt
  args:
    chdir: /app